import type { Community, Cooperative } from '@/app/dashboard/CommunityProfile/_logics/interface'

export const REGIONS = [
  { code: 'SA', name: 'Savannah',      districts: ['North Gonja', 'East Gonja', 'Central Gonja', 'West Gonja', 'Sawla-Tuna-Kalba', 'Bole'] },
  { code: 'AH', name: 'Ashanti',       districts: ['Kumasi Metro', 'Kwabre East', 'Oforikrom', 'Asokwa', 'Suame', 'Bosomtwe', 'Ejisu'] },
  { code: 'NR', name: 'Northern',      districts: ['Tamale Metro', 'Sagnarigu', 'Kumbungu', 'Tolon', 'Nanton', 'Karaga'] },
  { code: 'UE', name: 'Upper East',    districts: ['Bolgatanga Municipal', 'Bongo', 'Builsa North', 'Kassena-Nankana', 'Talensi', 'Nabdam'] },
  { code: 'UW', name: 'Upper West',    districts: ['Wa Municipal', 'Jirapa', 'Lawra', 'Nandom', 'Sissala East', 'Sissala West'] },
  { code: 'NE', name: 'North East',    districts: ['East Mamprusi', 'Mamprugu Moagduri', 'Bunkpurugu', 'Chereponi', 'Yunyoo-Nasuan'] },
  { code: 'BA', name: 'Bono Ahafo',    districts: ['Sunyani Municipal', 'Techiman', 'Wenchi', 'Dormaa Central', 'Tain', 'Berekum'] },
  { code: 'BE', name: 'Bono',          districts: ['Sunyani Municipal', 'Dormaa East', 'Tain', 'Wenchi', 'Jaman North', 'Jaman South'] },
  { code: 'CE', name: 'Central',       districts: ['Cape Coast Metro', 'Komenda-Edina', 'Mfantsiman', 'Gomoa West', 'Effutu', 'Assin North'] },
  { code: 'EP', name: 'Eastern',       districts: ['New Juaben', 'Kwahu North', 'Birim Central', 'Fanteakwa', 'Yilo Krobo', 'Akuapim North'] },
  { code: 'VR', name: 'Volta',         districts: ['Ho Municipal', 'Hohoe', 'Keta', 'Kpando', 'Afadjato South', 'South Tongu'] },
  { code: 'OT', name: 'Oti',           districts: ['Dambai', 'Kadjebi', 'Krachi East', 'Nkwanta North', 'Nkwanta South'] },
  { code: 'WR', name: 'Western',       districts: ['Sekondi-Takoradi', 'Ahanta West', 'Nzema East', 'Shama', 'Tarkwa-Nsuaem'] },
  { code: 'WN', name: 'Western North', districts: ['Sefwi Wiawso', 'Bibiani', 'Bodi', 'Bia East', 'Suaman'] },
  { code: 'AA', name: 'Greater Accra', districts: ['Accra Metro', 'Tema Metro', 'Ga East', 'Ga West', 'Adentan', 'Ledzokuku'] },
  { code: 'SW', name: 'Ahafo',         districts: ['Asunafo North', 'Asunafo South', 'Asutifi North', 'Asutifi South', 'Tano North', 'Tano South'] },
]

const A = (present: boolean | null, quantity: number | null = null, comment: string | null = null) =>
  ({ present, quantity, comment })

export const COMMUNITIES: Community[] = [
  {
    id: 'com-001',
    name: 'Gurubagu',
    regionCode: 'SA', regionName: 'Savannah',
    district: 'North Gonja', nearestTown: 'Damongo',
    socioeconomicStatus: 'rural',
    incomeStreams: ['farming'],
    incomeStreamsOther: null,
    socialAmenities: {
      schools:   A(true,  3),
      hospital:  A(false),
      police:    A(false),
      water:     A(true,  1),
      financial: A(false),
      road:      A(true,  null, 'Tarred road to Damongo'),
      network:   A(true,  null, 'MTN only'),
    },
    gpsLat: 9.4221, gpsLng: -1.5832,
    leaderName: 'Chief Alhassan', leaderContact: '+233201234567',
    imageUrl: null, createdAt: '2026-06-01',
  },
  {
    id: 'com-002',
    name: 'Lingbensi',
    regionCode: 'SA', regionName: 'Savannah',
    district: 'North Gonja', nearestTown: 'Daboya',
    socioeconomicStatus: 'rural',
    incomeStreams: ['farming', 'trading'],
    incomeStreamsOther: null,
    socialAmenities: {
      schools:   A(true,  5),
      hospital:  A(true,  2),
      police:    A(false),
      water:     A(true,  2),
      financial: A(false),
      road:      A(false),
      network:   A(true,  2),
    },
    gpsLat: 9.5735, gpsLng: -1.4106,
    leaderName: 'Tommy Basig Timothy', leaderContact: null,
    imageUrl: null, createdAt: '2026-06-02',
  },
  {
    id: 'com-003',
    name: 'Lingbensi Test',
    regionCode: 'SA', regionName: 'Savannah',
    district: 'North Gonja', nearestTown: null,
    socioeconomicStatus: 'peri_urban',
    incomeStreams: ['farming', 'trading'],
    incomeStreamsOther: null,
    socialAmenities: {
      schools:   A(null),
      hospital:  A(null),
      police:    A(null),
      water:     A(null),
      financial: A(null),
      road:      A(null),
      network:   A(null),
    },
    gpsLat: null, gpsLng: null,
    leaderName: 'Chief Razak', leaderContact: null,
    imageUrl: null, createdAt: '2026-06-10',
  },
  {
    id: 'com-004',
    name: 'Adum',
    regionCode: 'AH', regionName: 'Ashanti',
    district: 'Kumasi Metro', nearestTown: 'Kumasi',
    socioeconomicStatus: 'urban',
    incomeStreams: ['farming', 'trading'],
    incomeStreamsOther: null,
    socialAmenities: {
      schools:   A(true,  8),
      hospital:  A(true,  3),
      police:    A(true,  2),
      water:     A(true,  null),
      financial: A(true,  5),
      road:      A(true,  null),
      network:   A(true,  null, 'MTN, Telecel, AirtelTigo'),
    },
    gpsLat: 6.6930, gpsLng: -1.6215,
    leaderName: 'Nana Kwame Boateng', leaderContact: '+233241234567',
    imageUrl: null, createdAt: '2026-06-12',
  },
  {
    id: 'com-005',
    name: 'Mamponteng',
    regionCode: 'AH', regionName: 'Ashanti',
    district: 'Kwabre East', nearestTown: 'Mamponteng',
    socioeconomicStatus: 'peri_urban',
    incomeStreams: ['farming'],
    incomeStreamsOther: null,
    socialAmenities: {
      schools:   A(true,  2),
      hospital:  A(false),
      police:    A(false),
      water:     A(true,  1),
      financial: A(false),
      road:      A(true,  null),
      network:   A(true,  null, 'MTN only'),
    },
    gpsLat: 6.7805, gpsLng: -1.5432,
    leaderName: 'Opanyin Asare', leaderContact: '+233551234568',
    imageUrl: null, createdAt: '2026-06-14',
  },
]

export const COOPERATIVES: Cooperative[] = [
  {
    id: 'coop-001',
    name: 'Kanyita',
    communityId: 'com-001', communityName: 'Gurubagu', communityRegion: 'Savannah',
    memberCount: 40,
    primaryCrops: ['soybean', 'maize'],
    secondaryCrops: ['yam'],
    farmAnimals: [],
    chairmanName: 'Amina Alhassan',
    secretaryName: 'Mariama Ansah',
    createdAt: '2026-06-01',
  },
  {
    id: 'coop-002',
    name: 'Nabegim Test 1',
    communityId: 'com-002', communityName: 'Lingbensi', communityRegion: 'Savannah',
    memberCount: 40,
    primaryCrops: ['soybean'],
    secondaryCrops: ['maize'],
    farmAnimals: [],
    chairmanName: 'Bernard',
    secretaryName: null,
    createdAt: '2026-06-02',
  },
  {
    id: 'coop-003',
    name: 'Kumasi Maize Growers',
    communityId: 'com-004', communityName: 'Adum', communityRegion: 'Ashanti',
    memberCount: 25,
    primaryCrops: ['maize'],
    secondaryCrops: ['groundnut'],
    farmAnimals: ['cattle', 'goats'],
    chairmanName: 'Kofi Acheampong',
    secretaryName: 'Akosua Mensah',
    createdAt: '2026-06-13',
  },
]
