import type { FRIFarmer } from '@/app/dashboard/FRIDashboard/_logics/interface'

export const PILLARS_EMPTY = [
  { code: 'P1', name: 'Farm Management',    score: 0, max: 30, color: '#2C5F3F' },
  { code: 'P2', name: 'Climate Resilience', score: 0, max: 30, color: '#2B7BB9' },
  { code: 'P3', name: 'Economic Inclusion', score: 0, max: 20, color: '#E8963A' },
  { code: 'P4', name: 'Social Welfare',     score: 0, max: 20, color: '#D94F3D' },
]

export const BASELINE_PILLARS_EMPTY = [
  { code: 'P1', name: 'Agronomy',   score: 0, max: 30, color: '#2C5F3F' },
  { code: 'P2', name: 'CSA',        score: 0, max: 30, color: '#2B7BB9' },
  { code: 'P3', name: 'Advisory',   score: 0, max: 20, color: '#E8963A' },
  { code: 'P4', name: 'Enterprise', score: 0, max: 20, color: '#D94F3D' },
]

export const CHECKIN_ITEMS_EMPTY = [
  { name: 'Farming Experience',     pillar: 'P1', value: false },
  { name: 'Weed Management',        pillar: 'P1', value: false },
  { name: 'Proper Planting',        pillar: 'P1', value: false },
  { name: 'Fertilizer Use',         pillar: 'P1', value: false },
  { name: 'Pest & Disease Control', pillar: 'P1', value: false },
  { name: 'Mulching',               pillar: 'P2', value: false },
  { name: 'Composting',             pillar: 'P2', value: false },
  { name: 'Crop Rotation',          pillar: 'P2', value: false },
  { name: 'Water Harvesting',       pillar: 'P2', value: false },
  { name: 'Conservation Tillage',   pillar: 'P2', value: false },
  { name: 'Attends Training',       pillar: 'P3', value: false },
  { name: 'Follows Agronomist',     pillar: 'P3', value: false },
  { name: 'Cooperative Visits',     pillar: 'P3', value: false },
  { name: 'Cooperative Membership', pillar: 'P3', value: false },
  { name: 'Repayment History',      pillar: 'P4', value: false },
  { name: 'Savings Habit',          pillar: 'P4', value: false },
  { name: 'Additional Income',      pillar: 'P4', value: false },
  { name: 'Offtaker Confirmed',     pillar: 'P4', value: false },
]

export const AMA_BASELINE_ITEMS = [
  { name: 'Farming Experience',      pillar: 'P1', score: 4, max: 6 },
  { name: 'Weed Management',         pillar: 'P1', score: 3, max: 6 },
  { name: 'Proper Planting',         pillar: 'P1', score: 3, max: 6 },
  { name: 'Fertilizer Use',          pillar: 'P1', score: 3, max: 6 },
  { name: 'Pest & Disease Control',  pillar: 'P1', score: 3, max: 6 },
  { name: 'Mulching',                pillar: 'P2', score: 3, max: 6 },
  { name: 'Composting',              pillar: 'P2', score: 4, max: 6 },
  { name: 'Crop Rotation',           pillar: 'P2', score: 5, max: 6 },
  { name: 'Water Harvesting',        pillar: 'P2', score: 5, max: 6 },
  { name: 'Conservation Tillage',    pillar: 'P2', score: 5, max: 6 },
  { name: 'Attends Training',        pillar: 'P3', score: 3, max: 5 },
  { name: 'Follows Agronomist',      pillar: 'P3', score: 2, max: 5 },
  { name: 'Cooperative Visits',      pillar: 'P3', score: 2, max: 5 },
  { name: 'Cooperative Affiliation', pillar: 'P3', score: 3, max: 5 },
  { name: 'Repayment History',       pillar: 'P4', score: 5, max: 8 },
  { name: 'Savings Habit',           pillar: 'P4', score: 2, max: 4 },
  { name: 'Additional Income',       pillar: 'P4', score: 2, max: 4 },
  { name: 'Offtaker Confirmed',      pillar: 'P4', score: 4, max: 4 },
]

export const AMA_ECI_ITEMS = [
  { name: 'Stable Income & Debt Burden',  pillar: 'ECI', score: 6, max: 8 },
  { name: 'Moderate Financial Stability', pillar: 'ECI', score: 4, max: 8 },
  { name: 'Identity & Eligibility',       pillar: 'ECI', score: 6, max: 8 },
  { name: 'Production Commitment',        pillar: 'ECI', score: 6, max: 8 },
  { name: 'Declaration & Consent',        pillar: 'ECI', score: 5, max: 8 },
]

export const FARMERS: FRIFarmer[] = [
  {
    id: 'f-002', fullName: 'Ama Konadu', phone: '0551234568', nationalId: 'GHA-0000000002',
    gender: 'Female', dateOfBirth: '1992-06-14', community: 'Mamponteng',
    region: 'Ashanti', district: 'Kwabre East',
    primaryCrop: 'Maize', farmSize: '3.0', verified: false,
    programId: 'prog-002', programName: 'Maize Season 2026A',
    cohortId: 'coh-005', cohortName: 'Kumasi Cohort A',
    agentName: 'Abdul Razak', enrolledDate: '2026-06-09', enrollStatus: 'active',
    currentFri: null, currentZone: null, creditRisk: null,
    recommendation: null, scoreWeek: 0,
    baselineDone: false, baselineDate: null,
    checkinCount: 0, verifiedCheckins: 0, helpRequested: false, friTrend: null,
    pillars: PILLARS_EMPTY, baselinePillars: BASELINE_PILLARS_EMPTY,
    baselineItems: [], eci: null, eciItems: [], checkins: [],
  },
  {
    id: 'f-001', fullName: 'Ama Mensah', phone: '0241234567', nationalId: 'GHA-0000000001',
    gender: 'Female', dateOfBirth: '1990-03-12', community: 'Adum',
    region: 'Ashanti', district: 'Kumasi Metro',
    primaryCrop: 'Maize', farmSize: '2.5', verified: true,
    programId: 'prog-002', programName: 'Maize Season 2026A',
    cohortId: 'coh-005', cohortName: 'Kumasi Cohort A',
    agentName: 'Kwame Asante', enrolledDate: '2026-06-09', enrollStatus: 'active',
    currentFri: 61, currentZone: 'Resilience Builder', creditRisk: 'Medium Risk',
    recommendation: 'Approve — Standard', scoreWeek: 0,
    baselineDone: true, baselineDate: '2026-06-09',
    checkinCount: 2, verifiedCheckins: 1, helpRequested: false, friTrend: 'up',
    pillars: [
      { code: 'P1', name: 'Farm Management',    score: 16, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'Climate Resilience', score: 22, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Economic Inclusion', score: 10, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Social Welfare',     score: 13, max: 20, color: '#D94F3D' },
    ],
    baselinePillars: [
      { code: 'P1', name: 'Agronomy',   score: 16, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'CSA',        score: 22, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Advisory',   score: 10, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Enterprise', score: 13, max: 20, color: '#D94F3D' },
    ],
    baselineItems: AMA_BASELINE_ITEMS,
    eci: { score: 27, max: 40, criteria: 5 },
    eciItems: AMA_ECI_ITEMS,
    checkins: [
      {
        week: 25, date: '2026-06-15', verified: true, helpNeeded: true,
        pillarScores: { p1: 0, p2: 0, p3: 0, p4: 0 },
        items: CHECKIN_ITEMS_EMPTY,
      },
      {
        week: 24, date: '2026-06-09', verified: true, helpNeeded: false,
        pillarScores: { p1: 14, p2: 18, p3: 8, p4: 10 },
        items: CHECKIN_ITEMS_EMPTY.map((it, i) => ({ ...it, value: i % 3 !== 0 })),
      },
    ],
  },
  {
    id: 'f-003', fullName: 'Faiza Sidik', phone: '0551234567', nationalId: 'GHA-112233445-6',
    gender: 'Female', dateOfBirth: '1995-11-05', community: 'Gurubagu',
    region: 'Savannah', district: 'North Gonja',
    primaryCrop: 'Soybean', farmSize: '2.5', verified: true,
    programId: 'prog-001', programName: 'WAVE Program',
    cohortId: 'coh-001', cohortName: 'Cohort 1 - Gurubagu',
    agentName: 'Abdul Razak', enrolledDate: '2026-05-01', enrollStatus: 'active',
    currentFri: 82, currentZone: 'Resilience Leader', creditRisk: 'Low Risk',
    recommendation: 'Approve — Premium', scoreWeek: 2,
    baselineDone: true, baselineDate: '2026-05-14',
    checkinCount: 0, verifiedCheckins: 0, helpRequested: false, friTrend: 'flat',
    pillars: [
      { code: 'P1', name: 'Farm Management',    score: 25, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'Climate Resilience', score: 24, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Economic Inclusion', score: 18, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Social Welfare',     score: 15, max: 20, color: '#D94F3D' },
    ],
    baselinePillars: [
      { code: 'P1', name: 'Agronomy',   score: 25, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'CSA',        score: 24, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Advisory',   score: 18, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Enterprise', score: 15, max: 20, color: '#D94F3D' },
    ],
    baselineItems: [], eci: { score: 34, max: 40, criteria: 5 }, eciItems: [], checkins: [],
  },
  {
    id: 'f-004', fullName: 'Karma Fuseini', phone: '0201234567', nationalId: 'GHA-556677889-1',
    gender: 'Female', dateOfBirth: '1990-07-30', community: 'Lingbensi',
    region: 'Savannah', district: 'Central Gonja',
    primaryCrop: 'Soybean', farmSize: '5.0', verified: false,
    programId: 'prog-001', programName: 'WAVE Program',
    cohortId: 'coh-003', cohortName: 'Cohort 3 - Lingbensi',
    agentName: 'Kwame Asante', enrolledDate: '2026-05-15', enrollStatus: 'active',
    currentFri: 55, currentZone: 'Resilience Learner', creditRisk: 'Medium Risk',
    recommendation: 'Monitor — Conditional', scoreWeek: 1,
    baselineDone: true, baselineDate: '2026-05-28',
    checkinCount: 0, verifiedCheckins: 0, helpRequested: false, friTrend: null,
    pillars: [
      { code: 'P1', name: 'Farm Management',    score: 18, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'Climate Resilience', score: 16, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Economic Inclusion', score: 11, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Social Welfare',     score: 10, max: 20, color: '#D94F3D' },
    ],
    baselinePillars: [
      { code: 'P1', name: 'Agronomy',   score: 18, max: 30, color: '#2C5F3F' },
      { code: 'P2', name: 'CSA',        score: 16, max: 30, color: '#2B7BB9' },
      { code: 'P3', name: 'Advisory',   score: 11, max: 20, color: '#E8963A' },
      { code: 'P4', name: 'Enterprise', score: 10, max: 20, color: '#D94F3D' },
    ],
    baselineItems: [], eci: { score: 21, max: 40, criteria: 5 }, eciItems: [], checkins: [],
  },
  {
    id: 'f-005', fullName: 'Lydia Adjei', phone: '0501234567', nationalId: 'GHA-334455667-8',
    gender: 'Female', dateOfBirth: '1985-01-18', community: 'Kajetia',
    region: 'Central', district: 'Gomoa West',
    primaryCrop: 'Cassava', farmSize: '2.0', verified: true,
    programId: 'prog-002', programName: 'Maize Season 2026A',
    cohortId: 'coh-004', cohortName: 'Kajetia Batch 1',
    agentName: 'Kwame Asante', enrolledDate: '2026-06-01', enrollStatus: 'active',
    currentFri: null, currentZone: null, creditRisk: null,
    recommendation: null, scoreWeek: 0,
    baselineDone: false, baselineDate: null,
    checkinCount: 0, verifiedCheckins: 0, helpRequested: true, friTrend: null,
    pillars: PILLARS_EMPTY, baselinePillars: BASELINE_PILLARS_EMPTY,
    baselineItems: [], eci: null, eciItems: [], checkins: [],
  },
  {
    id: 'f-007', fullName: 'Salamatu Fuseini', phone: '0241234568', nationalId: 'GHA-778899001-3',
    gender: 'Female', dateOfBirth: '1988-04-22', community: 'Damongo',
    region: 'Savannah', district: 'North Gonja',
    primaryCrop: 'Soybean', farmSize: '0', verified: false,
    programId: null, programName: null, cohortId: null, cohortName: null,
    agentName: null, enrolledDate: null, enrollStatus: null,
    currentFri: null, currentZone: null, creditRisk: null,
    recommendation: null, scoreWeek: 0,
    baselineDone: false, baselineDate: null,
    checkinCount: 0, verifiedCheckins: 0, helpRequested: false, friTrend: null,
    pillars: PILLARS_EMPTY, baselinePillars: BASELINE_PILLARS_EMPTY,
    baselineItems: [], eci: null, eciItems: [], checkins: [],
  },
]
