import type { Intervention } from '@/app/dashboard/OpportunityPathways/_logics/interface'

export const INTERVENTIONS: Intervention[] = [
  {
    id:               'int-001',
    name:             'Maize Input Loan',
    type:             'Input Loan',
    season:           '2026A',
    valueDescription: 'GHS 1,800',
    description:      'Subsidised inputs package covering certified maize seeds, NPK fertiliser, and crop protectants for one season.',
    minFri:           60,
    capacity:         200,
    status:           'Active',
    approval:         'Auto',
    enrolledCohorts: [
      { programId: 'prog-002', programName: 'Maize Season 2026A', cohortId: 'coh-005', cohortName: 'Kumasi Cohort A' },
    ],
    rules: [
      { id: 'r-001', field: 'primaryCrop', operator: '=',  value: 'maize' },
      { id: 'r-002', field: 'farmSize',    operator: '>=', value: '0.5'   },
    ],
    steps: [
      { id: 's-001', description: 'Agent verifies farm size and crop type on field visit.', order: 1 },
      { id: 's-002', description: 'Farmer completes input request form with agent.',         order: 2 },
      { id: 's-003', description: 'Inputs disbursed at collection point within 7 days.',    order: 3 },
    ],
    createdAt: '2026-03-01',
  },
  {
    id:               'int-002',
    name:             'Climate-Smart Insurance',
    type:             'Insurance',
    season:           '2026A',
    valueDescription: 'Up to GHS 3,000',
    description:      'Index-based weather insurance covering drought and flood events. Payout triggered automatically by satellite weather data.',
    minFri:           65,
    capacity:         300,
    status:           'Active',
    approval:         'Auto',
    enrolledCohorts: [
      { programId: 'prog-002', programName: 'Maize Season 2026A', cohortId: 'coh-005', cohortName: 'Kumasi Cohort A' },
      { programId: 'prog-001', programName: 'WAVE Program',       cohortId: 'coh-001', cohortName: 'Cohort 1 - Gurubagu' },
    ],
    rules: [
      { id: 'r-003', field: 'primaryCrop', operator: '=',  value: 'maize' },
      { id: 'r-004', field: 'fri',         operator: '>=', value: '65'    },
    ],
    steps: [
      { id: 's-004', description: 'Farmer enrolled automatically upon meeting FRI threshold.', order: 1 },
      { id: 's-005', description: 'Policy document sent via SMS within 48 hours.',             order: 2 },
    ],
    createdAt: '2026-03-01',
  },
  {
    id:               'int-003',
    name:             'Soybean Input Loan',
    type:             'Input Loan',
    season:           '2026A',
    valueDescription: 'GHS 1,400',
    description:      'Inputs package — improved soybean seeds, inoculants, and fertilisers for the 2026A planting season.',
    minFri:           60,
    capacity:         100,
    status:           'Active',
    approval:         'Manual',
    enrolledCohorts: [
      { programId: 'prog-001', programName: 'WAVE Program', cohortId: 'coh-001', cohortName: 'Cohort 1 - Gurubagu' },
      { programId: 'prog-001', programName: 'WAVE Program', cohortId: 'coh-002', cohortName: 'Cohort 2 - Watato'   },
    ],
    rules: [
      { id: 'r-005', field: 'primaryCrop', operator: '=', value: 'soybean' },
    ],
    steps: [
      { id: 's-006', description: 'Agent confirms farm details and completes eligibility check.',   order: 1 },
      { id: 's-007', description: 'Programme officer approves application within 3 working days.', order: 2 },
      { id: 's-008', description: 'Inputs collected at district aggregation point.',               order: 3 },
    ],
    createdAt: '2026-01-10',
  },
  {
    id:               'int-004',
    name:             'Market Linkage — Premium Offtake',
    type:             'Market Access',
    season:           '2026A',
    valueDescription: 'Premium pricing',
    description:      'Direct offtake agreement with certified buyers guaranteeing Grade A soybean purchase at 15% above market rate.',
    minFri:           75,
    capacity:         50,
    status:           'Draft',
    approval:         'Manual',
    enrolledCohorts:  [],
    rules: [
      { id: 'r-006', field: 'fri',      operator: '>=', value: '75'   },
      { id: 'r-007', field: 'verified', operator: '=',  value: 'true' },
    ],
    steps: [
      { id: 's-009', description: 'Farmer submits produce volume estimate 4 weeks before harvest.', order: 1 },
      { id: 's-010', description: 'Offtake agreement signed with buyer representative.',             order: 2 },
    ],
    createdAt: '2026-02-20',
  },
]
