-- Extended farmer profile fields
ALTER TABLE farmers
  ADD COLUMN IF NOT EXISTS first_name             text,
  ADD COLUMN IF NOT EXISTS last_name              text,
  ADD COLUMN IF NOT EXISTS national_id_type       text DEFAULT 'ghana_card',
  ADD COLUMN IF NOT EXISTS id_front_url           text,
  ADD COLUMN IF NOT EXISTS id_back_url            text,
  ADD COLUMN IF NOT EXISTS voice_consent_url      text,
  ADD COLUMN IF NOT EXISTS cooperative_id         uuid REFERENCES cooperatives(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS program_id             uuid REFERENCES programs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS cohort_id_ref          uuid REFERENCES cohorts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS years_farm_experience  integer,
  ADD COLUMN IF NOT EXISTS acres_cultivated       numeric,
  ADD COLUMN IF NOT EXISTS secondary_crop         text,
  ADD COLUMN IF NOT EXISTS secondary_crop_other   text,
  ADD COLUMN IF NOT EXISTS primary_crop_other     text,
  ADD COLUMN IF NOT EXISTS primary_bags_prev_season   integer,
  ADD COLUMN IF NOT EXISTS secondary_bags_prev_season integer,
  ADD COLUMN IF NOT EXISTS owns_tractor           boolean,
  ADD COLUMN IF NOT EXISTS owns_house             boolean,
  ADD COLUMN IF NOT EXISTS marital_status         text,
  ADD COLUMN IF NOT EXISTS wives_count            integer,
  ADD COLUMN IF NOT EXISTS children_count         integer,
  ADD COLUMN IF NOT EXISTS other_business         boolean,
  ADD COLUMN IF NOT EXISTS other_business_specify text,
  ADD COLUMN IF NOT EXISTS is_community_native    boolean,
  ADD COLUMN IF NOT EXISTS origin_if_not_native   text,
  ADD COLUMN IF NOT EXISTS community_preferences  text[],
  ADD COLUMN IF NOT EXISTS other_agric_companies  boolean,
  ADD COLUMN IF NOT EXISTS other_agric_companies_specify text,
  ADD COLUMN IF NOT EXISTS desired_assets         text[],
  ADD COLUMN IF NOT EXISTS input_credit_participation boolean,
  ADD COLUMN IF NOT EXISTS other_org_engagement   boolean,
  ADD COLUMN IF NOT EXISTS other_org_activities   text,
  ADD COLUMN IF NOT EXISTS other_org_name         text,
  ADD COLUMN IF NOT EXISTS asinyo_improvement_notes text,
  ADD COLUMN IF NOT EXISTS is_draft               boolean DEFAULT false;
