-- Rewrite all check-in question labels and descriptions to first-person ownership statements
-- Farmers affirm behaviours they own, rather than answering a survey about themselves
DO $$
DECLARE org_id uuid := '00000000-0000-0000-0000-000000000001';
BEGIN

-- ── MAIZE WEEK 1 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I ploughed my land',                         description = 'I tilled my plot to the recommended depth for a good seedbed.'                                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%plough%';
UPDATE checkin_questions SET label = 'I conducted a soil test',                    description = 'I had my soil tested this season to guide my fertiliser decisions.'                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%soil test%';
UPDATE checkin_questions SET label = 'I managed my crop residue',                  description = 'I incorporated or cleared the previous season''s crop residue from my plot.'                        WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%residue%';
UPDATE checkin_questions SET label = 'I put contour ridges / bunds in place',      description = 'I have erosion-control structures in place on my sloping land.'                                     WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%contour%';
UPDATE checkin_questions SET label = 'I attended the pre-season training',         description = 'I participated in the pre-season advisory session.'                                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%training%';
UPDATE checkin_questions SET label = 'I prepared my input budget',                 description = 'I prepared a budget for my inputs this season.'                                                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 1 AND label ILIKE '%budget%';

-- ── MAIZE WEEK 2 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I used certified seed',                      description = 'I planted with certified or improved variety seed.'                                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%certified seed%';
UPDATE checkin_questions SET label = 'I planted at the correct seed rate',         description = 'I planted within the recommended density of 25,000–35,000 plants per hectare.'                     WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%seed rate%';
UPDATE checkin_questions SET label = 'I planted at the correct depth',             description = 'I planted my seed at the recommended depth of 5–7 cm.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%planting depth%';
UPDATE checkin_questions SET label = 'I aligned my planting to the rainfall forecast', description = 'I timed my planting according to the seasonal rainfall forecast.'                               WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%forecast%';
UPDATE checkin_questions SET label = 'I followed the planting advisory',           description = 'I followed the recommended planting guidance from my agent.'                                         WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%planting advisory%';
UPDATE checkin_questions SET label = 'I procured my inputs on time',               description = 'I had all required inputs ready at planting time.'                                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 2 AND label ILIKE '%inputs procured%';

-- ── MAIZE WEEK 3 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My germination rate is satisfactory',        description = 'My crop germinated to at least 80% of planted stands.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 3 AND label ILIKE '%germination rate%';
UPDATE checkin_questions SET label = 'I filled all gaps by replanting',            description = 'I replanted all gaps and missing stands within 5 days.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 3 AND label ILIKE '%gap%';
UPDATE checkin_questions SET label = 'My soil moisture is adequate',               description = 'My seedlings have sufficient soil moisture for early establishment.'                                 WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 3 AND label ILIKE '%soil moisture%';
UPDATE checkin_questions SET label = 'I had my early field visit with the agent',  description = 'My agent visited my field to confirm stand establishment.'                                           WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 3 AND label ILIKE '%early visit%';
UPDATE checkin_questions SET label = 'I sourced labour for replanting',            description = 'I had labour ready promptly for gap filling.'                                                        WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 3 AND label ILIKE '%labour%';

-- ── MAIZE WEEK 4 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I applied my basal fertiliser',              description = 'I applied the recommended basal fertiliser (e.g. NPK) to my crop.'                                 WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%basal fertiliser%';
UPDATE checkin_questions SET label = 'I applied fertiliser at the correct rate',   description = 'I applied fertiliser at the recommended rate per hectare.'                                          WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%application rate%';
UPDATE checkin_questions SET label = 'I placed my fertiliser correctly',           description = 'I banded or placed fertiliser correctly to avoid burning my crop.'                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%placement%';
UPDATE checkin_questions SET label = 'I timed my fertiliser application with rainfall', description = 'I applied fertiliser before or just after rainfall to reduce nutrient losses.'                WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%timed with rain%';
UPDATE checkin_questions SET label = 'I followed the fertiliser advisory',         description = 'I applied the fertiliser type recommended by my agent.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%fertiliser advisory%';
UPDATE checkin_questions SET label = 'I recorded my fertiliser cost',              description = 'I entered the cost of fertiliser in my farm record book.'                                            WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 4 AND label ILIKE '%fertiliser cost%';

-- ── MAIZE WEEK 5 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I completed my first weeding',               description = 'I weeded my plot before the crop reached the 3–4 leaf stage.'                                      WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 5 AND label ILIKE '%weeding%';
UPDATE checkin_questions SET label = 'I applied herbicide correctly',              description = 'I applied herbicide at the correct rate and at the right timing.'                                    WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 5 AND label ILIKE '%herbicide%';
UPDATE checkin_questions SET label = 'I applied mulch to my plot',                 description = 'I applied mulch to suppress weeds and retain soil moisture.'                                        WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 5 AND label ILIKE '%mulch%';
UPDATE checkin_questions SET label = 'I scouted for weeds with my agent',          description = 'My agent and I conducted a joint weed assessment on my plot.'                                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 5 AND label ILIKE '%weed scouting%';
UPDATE checkin_questions SET label = 'I recorded my weed management cost',         description = 'I recorded the cost of weeding — labour and herbicide — in my farm records.'                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 5 AND label ILIKE '%weed cost%';

-- ── MAIZE WEEK 6 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I scouted my crop for Fall Armyworm',        description = 'I checked my crop for FAW egg masses and damage signs.'                                             WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%FAW%';
UPDATE checkin_questions SET label = 'I applied the appropriate pest control',     description = 'I applied the recommended control measure after detecting pests.'                                    WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%pest control%';
UPDATE checkin_questions SET label = 'I checked my crop for disease symptoms',     description = 'I inspected my crop for foliar disease symptoms such as grey leaf spot or streak virus.'           WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%disease symptoms%';
UPDATE checkin_questions SET label = 'I maintained field hygiene',                 description = 'I removed and destroyed heavily infected plant material from my plot.'                               WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%hygiene%';
UPDATE checkin_questions SET label = 'I reported pest and disease to my agent',    description = 'I reported any pest or disease outbreaks to my agent promptly.'                                     WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%pest report%';
UPDATE checkin_questions SET label = 'I recorded my pest control cost',            description = 'I recorded the costs of pest and disease management in my farm records.'                            WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 6 AND label ILIKE '%pest control cost%';

-- ── MAIZE WEEK 7 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I applied my top-dressing fertiliser',       description = 'I applied urea or CAN as top-dressing at the right crop stage.'                                    WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 7 AND label ILIKE '%top-dress%';
UPDATE checkin_questions SET label = 'I checked for micronutrient deficiency',     description = 'I inspected my crop for zinc or sulphur deficiency symptoms.'                                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 7 AND label ILIKE '%micronutrient%';
UPDATE checkin_questions SET label = 'I managed moisture during rapid crop growth', description = 'I managed moisture stress on my crop during the rapid growth phase.'                               WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 7 AND label ILIKE '%irrigation%';
UPDATE checkin_questions SET label = 'I followed the nutrient advisory',           description = 'I applied top-dressing as recommended by my agent.'                                                  WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 7 AND label ILIKE '%nutrient advisory%';
UPDATE checkin_questions SET label = 'I updated my input expenditure records',     description = 'I updated my total input expenditure in my farm records.'                                           WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 7 AND label ILIKE '%input expenditure%';

-- ── MAIZE WEEK 8 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My crop has reached tasselling stage',       description = 'My crop reached tasselling stage uniformly across the plot.'                                       WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 8 AND label ILIKE '%tasselling%';
UPDATE checkin_questions SET label = 'My silk emergence is uniform',               description = 'My silk emergence is synchronised with tassel pollen shed.'                                         WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 8 AND label ILIKE '%silk%';
UPDATE checkin_questions SET label = 'I managed moisture stress during flowering', description = 'I ensured my crop had adequate moisture during the critical flowering window.'                      WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 8 AND label ILIKE '%moisture stress%';
UPDATE checkin_questions SET label = 'I reported my flowering progress to my agent', description = 'I updated my agent on my crop''s flowering progress.'                                            WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 8 AND label ILIKE '%flowering progress%';
UPDATE checkin_questions SET label = 'I started my yield estimation',              description = 'I began a preliminary yield estimate based on cob set.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 8 AND label ILIKE '%yield estimation%';

-- ── MAIZE WEEK 9 ──────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My cobs are developing well',                description = 'My cobs are developing uniformly with good grain fill.'                                             WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 9 AND label ILIKE '%cob development%';
UPDATE checkin_questions SET label = 'I checked for late-season disease',          description = 'I scouted my crop for late-season diseases such as ear rot and aflatoxin risk.'                    WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 9 AND label ILIKE '%late-season disease%';
UPDATE checkin_questions SET label = 'I managed water and heat stress',            description = 'I managed water and heat stress on my crop during grain fill.'                                      WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 9 AND label ILIKE '%water stress%';
UPDATE checkin_questions SET label = 'I received grain fill guidance from my agent', description = 'My agent gave me guidance on managing my crop through the grain-fill period.'                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 9 AND label ILIKE '%grain fill advisory%';
UPDATE checkin_questions SET label = 'I prepared my harvest labour plan',          description = 'I planned the labour I need for the upcoming harvest.'                                               WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 9 AND label ILIKE '%labour plan%';

-- ── MAIZE WEEK 10 ─────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I assessed my crop maturity',                description = 'I checked my crop for maturity signs — husk colour, black layer, and kernel hardness.'            WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 10 AND label ILIKE '%maturity%';
UPDATE checkin_questions SET label = 'My crop is field-drying',                    description = 'My crop is drying adequately in the field before harvest.'                                          WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 10 AND label ILIKE '%drying%';
UPDATE checkin_questions SET label = 'I adjusted my harvest timing for the weather', description = 'I adjusted my harvest timing based on the weather forecast.'                                    WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 10 AND label ILIKE '%harvest timing%';
UPDATE checkin_questions SET label = 'I confirmed my harvest date with my agent',  description = 'I confirmed my planned harvest date with my agent.'                                                  WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 10 AND label ILIKE '%harvest date%';
UPDATE checkin_questions SET label = 'I arranged my market',                       description = 'I identified a buyer or market channel for my harvest.'                                              WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 10 AND label ILIKE '%market%';

-- ── MAIZE WEEK 11 ─────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I used the right harvesting method',         description = 'I harvested using the correct method — manual or mechanical — for my conditions.'                  WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 11 AND label ILIKE '%harvest method%';
UPDATE checkin_questions SET label = 'I minimised my harvest losses',              description = 'I kept my harvest losses below the recommended threshold.'                                           WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 11 AND label ILIKE '%losses%';
UPDATE checkin_questions SET label = 'I harvested during a dry weather window',    description = 'I timed my harvest to take advantage of a dry weather window.'                                      WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 11 AND label ILIKE '%weather window%';
UPDATE checkin_questions SET label = 'I shared my harvest data with my agent',     description = 'I reported my actual yield to my agent.'                                                             WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 11 AND label ILIKE '%harvest data%';
UPDATE checkin_questions SET label = 'I recorded my yield',                        description = 'I recorded my total yield in bags or kg in my farm record book.'                                   WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 11 AND label ILIKE '%yield recorded%';

-- ── MAIZE WEEK 12 ─────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I dried my grain to safe moisture',          description = 'I dried my grain to 13% moisture content or below before storage.'                                  WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%dried%';
UPDATE checkin_questions SET label = 'I stored my grain properly',                 description = 'I stored my grain in a clean, pest-free facility or hermetic bag.'                                  WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%stored%';
UPDATE checkin_questions SET label = 'I used climate-smart storage',               description = 'I used hermetic storage or metal silos to protect my grain from post-harvest losses.'               WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%storage method%';
UPDATE checkin_questions SET label = 'I completed the post-harvest debrief',       description = 'I attended or participated in the post-season debrief session.'                                     WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%debrief%';
UPDATE checkin_questions SET label = 'I calculated my gross margin',               description = 'I calculated my gross margin — revenue minus input costs — for this season.'                        WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%gross margin%';
UPDATE checkin_questions SET label = 'I started planning for next season',         description = 'I have begun planning my inputs and activities for the next season.'                                 WHERE organisation_id = org_id AND crop_type = 'maize' AND week_number = 12 AND label ILIKE '%next-season%';

-- ── SOYBEAN WEEK 1 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I ploughed and harrowed my land',            description = 'I prepared my plot to a fine tilth through ploughing and harrowing.'                               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%ploughed and harrowed%';
UPDATE checkin_questions SET label = 'I treated my seed with Rhizobium inoculant', description = 'I applied the correct Rhizobium inoculant to my seed before planting.'                            WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%Rhizobium%';
UPDATE checkin_questions SET label = 'I incorporated my previous crop residue',    description = 'I incorporated previous crop residue to improve my soil organic matter.'                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%residue%';
UPDATE checkin_questions SET label = 'I cleared my drainage channels',             description = 'I ensured my drainage channels are functional to prevent waterlogging.'                             WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%drainage%';
UPDATE checkin_questions SET label = 'I attended the pre-season training',         description = 'I participated in the pre-season soybean advisory session.'                                         WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%training%';
UPDATE checkin_questions SET label = 'I prepared my input budget',                 description = 'I prepared a budget for my soybean inputs this season.'                                             WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 1 AND label ILIKE '%budget%';

-- ── SOYBEAN WEEK 2 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I used certified soybean seed',              description = 'I planted with certified or improved soybean variety seed.'                                         WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%certified seed%';
UPDATE checkin_questions SET label = 'I observed the correct row spacing',         description = 'I planted my soybeans at 45–60 cm row spacing as recommended.'                                    WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%row spacing%';
UPDATE checkin_questions SET label = 'I planted at the correct seed rate',         description = 'I planted within the recommended seeding rate of 60–80 kg per hectare.'                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%seed rate%';
UPDATE checkin_questions SET label = 'I aligned my planting to the rainfall forecast', description = 'I timed my planting to coincide with the onset of reliable rains.'                            WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%forecast%';
UPDATE checkin_questions SET label = 'I followed the planting advisory',           description = 'I followed the recommended soybean planting guidance from my agent.'                                WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%planting advisory%';
UPDATE checkin_questions SET label = 'I procured my inputs on time',               description = 'I had all required inputs ready at planting time.'                                                   WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 2 AND label ILIKE '%inputs procured%';

-- ── SOYBEAN WEEK 3 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My germination rate is satisfactory',        description = 'My soybean crop germinated to at least 80% of planted stands.'                                     WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 3 AND label ILIKE '%germination%';
UPDATE checkin_questions SET label = 'I replanted all gaps',                       description = 'I replanted gaps in my stand promptly.'                                                              WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 3 AND label ILIKE '%replanting%';
UPDATE checkin_questions SET label = 'My soil moisture is adequate',               description = 'My seedlings have sufficient soil moisture for early establishment.'                                 WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 3 AND label ILIKE '%soil moisture%';
UPDATE checkin_questions SET label = 'I had my early field visit with the agent',  description = 'My agent visited my field to confirm stand establishment.'                                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 3 AND label ILIKE '%early visit%';
UPDATE checkin_questions SET label = 'I sourced labour for replanting',            description = 'I had labour ready promptly for gap filling.'                                                        WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 3 AND label ILIKE '%labour%';

-- ── SOYBEAN WEEK 4 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I completed my first weeding',               description = 'I weeded my soybean plot at the V1–V3 growth stage as recommended.'                               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 4 AND label ILIKE '%weeding%';
UPDATE checkin_questions SET label = 'I applied herbicide correctly',              description = 'I applied the correct herbicide product at the right rate.'                                          WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 4 AND label ILIKE '%herbicide%';
UPDATE checkin_questions SET label = 'I applied mulch to my plot',                 description = 'I applied mulch to conserve moisture and suppress weeds.'                                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 4 AND label ILIKE '%mulch%';
UPDATE checkin_questions SET label = 'I scouted for weeds with my agent',          description = 'My agent and I conducted a joint weed assessment on my plot.'                                       WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 4 AND label ILIKE '%weed scouting%';
UPDATE checkin_questions SET label = 'I recorded my weeding cost',                 description = 'I recorded the cost of weeding — labour and herbicide — in my farm records.'                       WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 4 AND label ILIKE '%weeding cost%';

-- ── SOYBEAN WEEK 5 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I scouted my crop for soybean aphids',       description = 'I checked my crop for aphid infestations at the threshold of 250 aphids per plant.'               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%aphid%';
UPDATE checkin_questions SET label = 'I applied the appropriate pest control',     description = 'I applied the recommended control measure after detecting pests.'                                    WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%pest control%';
UPDATE checkin_questions SET label = 'I checked for bacterial pustule and rust',   description = 'I inspected my crop for bacterial pustule and Asian soybean rust symptoms.'                        WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%pustule%';
UPDATE checkin_questions SET label = 'I maintained field hygiene',                 description = 'I removed and destroyed heavily infected plant material from my plot.'                               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%hygiene%';
UPDATE checkin_questions SET label = 'I reported pest and disease to my agent',    description = 'I reported any pest or disease outbreaks to my agent promptly.'                                     WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%pest report%';
UPDATE checkin_questions SET label = 'I recorded my pest control cost',            description = 'I recorded the costs of pest and disease management in my farm records.'                            WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 5 AND label ILIKE '%pest control cost%';

-- ── SOYBEAN WEEK 6 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My crop has started flowering',              description = 'My crop has reached the R1 first flower growth stage.'                                              WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 6 AND label ILIKE '%flowering commenced%';
UPDATE checkin_questions SET label = 'I assessed my nodule development',           description = 'I checked my crop roots and found effective pink or red-interior nodules present.'                 WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 6 AND label ILIKE '%nodule%';
UPDATE checkin_questions SET label = 'I managed moisture during flowering',        description = 'I managed moisture on my crop during the critical flowering period.'                                 WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 6 AND label ILIKE '%moisture stress%';
UPDATE checkin_questions SET label = 'I reported my flowering progress to my agent', description = 'I updated my agent on my crop''s flowering progress.'                                            WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 6 AND label ILIKE '%flowering progress%';
UPDATE checkin_questions SET label = 'I started my yield estimation',              description = 'I began a preliminary yield estimate based on flower set.'                                            WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 6 AND label ILIKE '%yield estimation%';

-- ── SOYBEAN WEEK 7 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My pod set is uniform',                      description = 'Pods are setting uniformly across my plot at the R3–R4 growth stage.'                              WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 7 AND label ILIKE '%pod set%';
UPDATE checkin_questions SET label = 'I scouted my crop for pod borers',           description = 'I checked my crop for pod-boring insects.'                                                          WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 7 AND label ILIKE '%pod borer%';
UPDATE checkin_questions SET label = 'I managed drought stress during pod set',    description = 'I managed drought stress on my crop during the pod set period.'                                     WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 7 AND label ILIKE '%drought%';
UPDATE checkin_questions SET label = 'I received pod-set guidance from my agent',  description = 'My agent gave me guidance on managing my crop through the pod-set period.'                         WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 7 AND label ILIKE '%pod-set advisory%';
UPDATE checkin_questions SET label = 'I prepared my harvest labour plan',          description = 'I planned the labour I need for the upcoming harvest.'                                               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 7 AND label ILIKE '%labour plan%';

-- ── SOYBEAN WEEK 8 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'My grain fill is satisfactory',              description = 'Seeds are developing fully within my pods at the R5–R6 growth stage.'                              WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 8 AND label ILIKE '%grain fill satisfactory%';
UPDATE checkin_questions SET label = 'I checked for late-season disease',          description = 'I scouted my crop for late-season foliar diseases.'                                                 WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 8 AND label ILIKE '%late-season disease%';
UPDATE checkin_questions SET label = 'I managed water and heat stress',            description = 'I managed water and heat stress on my crop during grain fill.'                                      WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 8 AND label ILIKE '%water stress%';
UPDATE checkin_questions SET label = 'I received grain fill guidance from my agent', description = 'My agent gave me guidance on managing my crop through the grain-fill period.'                   WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 8 AND label ILIKE '%grain fill advisory%';
UPDATE checkin_questions SET label = 'I updated my input expenditure records',     description = 'I updated my total input expenditure in my farm records.'                                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 8 AND label ILIKE '%input expenditure%';

-- ── SOYBEAN WEEK 9 ────────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I assessed my crop maturity',                description = 'I checked my crop for pod colour and leaf senescence at the R7–R8 growth stage.'                  WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 9 AND label ILIKE '%maturity%';
UPDATE checkin_questions SET label = 'My crop is field-drying',                    description = 'My crop is drying adequately in the field before harvest.'                                          WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 9 AND label ILIKE '%drying%';
UPDATE checkin_questions SET label = 'I adjusted my harvest timing for the weather', description = 'I adjusted my harvest timing based on the weather forecast.'                                    WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 9 AND label ILIKE '%harvest timing%';
UPDATE checkin_questions SET label = 'I confirmed my harvest date with my agent',  description = 'I confirmed my planned harvest date with my agent.'                                                  WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 9 AND label ILIKE '%harvest date%';
UPDATE checkin_questions SET label = 'I arranged my market',                       description = 'I identified a buyer or market channel for my harvest.'                                              WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 9 AND label ILIKE '%market%';

-- ── SOYBEAN WEEK 10 ───────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I used the right harvesting method',         description = 'I harvested using the correct method to minimise pod shatter.'                                      WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 10 AND label ILIKE '%harvest method%';
UPDATE checkin_questions SET label = 'I minimised my harvest losses',              description = 'I kept pod shatter and threshing losses below the recommended threshold.'                           WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 10 AND label ILIKE '%losses%';
UPDATE checkin_questions SET label = 'I harvested during a dry weather window',    description = 'I timed my harvest to take advantage of a dry weather window.'                                      WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 10 AND label ILIKE '%weather window%';
UPDATE checkin_questions SET label = 'I shared my harvest data with my agent',     description = 'I reported my actual yield to my agent.'                                                             WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 10 AND label ILIKE '%harvest data%';
UPDATE checkin_questions SET label = 'I recorded my yield',                        description = 'I recorded my total yield in bags or kg in my farm record book.'                                   WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 10 AND label ILIKE '%yield recorded%';

-- ── SOYBEAN WEEK 11 ───────────────────────────────────────────────────────
UPDATE checkin_questions SET label = 'I dried my grain to safe moisture',          description = 'I dried my soybean grain to 12% moisture content or below before storage.'                         WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%dried%';
UPDATE checkin_questions SET label = 'I stored my grain properly',                 description = 'I stored my grain in a clean, pest-free facility or hermetic bag.'                                  WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%stored%';
UPDATE checkin_questions SET label = 'I used climate-smart storage',               description = 'I used hermetic storage to protect my grain from post-harvest losses.'                               WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%storage method%';
UPDATE checkin_questions SET label = 'I completed the post-harvest debrief',       description = 'I attended or participated in the post-season debrief session.'                                     WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%debrief%';
UPDATE checkin_questions SET label = 'I calculated my gross margin',               description = 'I calculated my gross margin — revenue minus input costs — for this season.'                        WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%gross margin%';
UPDATE checkin_questions SET label = 'I started planning for next season',         description = 'I have begun planning my inputs and variety selection for the next season.'                         WHERE organisation_id = org_id AND crop_type = 'soybean' AND week_number = 11 AND label ILIKE '%next-season%';

END $$;
